# Generated by Django 5.0.4 on 2024-04-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapikeys',
            old_name='edemam_api_key',
            new_name='edamam_api_key',
        ),
        migrations.RenameField(
            model_name='userapikeys',
            old_name='edemam_app_id',
            new_name='edamam_app_id',
        ),
    ]
