# Generated by Django 5.0.4 on 2024-04-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userapikeys_edamam_api_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userallergies',
            old_name='mediterranean_free',
            new_name='Mediterranean',
        ),
    ]
