# Generated by Django 5.0.4 on 2024-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_mediterranean_free_userallergies_mediterranean'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(default=0),
        ),
    ]
