# Generated by Django 5.0.4 on 2024-04-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_calories_remove_profile_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.IntegerField(choices=[(0, 'Sedentary'), (1, 'Lightly active'), (2, 'Moderately active'), (3, 'Very active'), (4, 'Super active')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.IntegerField(choices=[(0, 'Maintain weight'), (1, 'Lose weight'), (2, 'Gain weight')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
    ]
