# Generated by Django 5.0.4 on 2024-04-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_activity_level_alter_profile_goal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='height',
            new_name='height_in_inches',
        ),
    ]
