# Generated by Django 5.0.4 on 2024-04-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_user_alter_recipe_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='items',
            new_name='items_count',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='site_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='last_seen_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_data',
            field=models.JSONField(default=dict),
        ),
    ]
