# Generated by Django 5.0.4 on 2024-04-19 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipes',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_macros', models.CharField(max_length=100)),
                ('recipe_ingredients', models.CharField(max_length=100)),
                ('recipe_image', models.CharField(max_length=100)),
                ('recipe_url', models.CharField(max_length=100)),
            ],
        ),
    ]
