# Generated by Django 5.0.4 on 2024-04-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedRecipes',
        ),
    ]
