# Generated by Django 5.0.4 on 2024-04-22 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('site_url', models.URLField(max_length=500)),
                ('calories', models.FloatField()),
                ('time_to_cook', models.IntegerField(help_text='Time in minutes')),
                ('fat', models.FloatField(help_text='Fat in grams')),
                ('carbs', models.FloatField(help_text='Carbohydrates in grams')),
                ('protein', models.FloatField(help_text='Protein in grams')),
                ('ingredients', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chinese_recipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('site_url', models.URLField(max_length=500)),
                ('calories', models.FloatField()),
                ('time_to_cook', models.IntegerField(help_text='Time in minutes')),
                ('fat', models.FloatField(help_text='Fat in grams')),
                ('carbs', models.FloatField(help_text='Carbohydrates in grams')),
                ('protein', models.FloatField(help_text='Protein in grams')),
                ('ingredients', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='french_recipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('site_url', models.URLField(max_length=500)),
                ('calories', models.FloatField()),
                ('time_to_cook', models.IntegerField(help_text='Time in minutes')),
                ('fat', models.FloatField(help_text='Fat in grams')),
                ('carbs', models.FloatField(help_text='Carbohydrates in grams')),
                ('protein', models.FloatField(help_text='Protein in grams')),
                ('ingredients', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='italian_recipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('site_url', models.URLField(max_length=500)),
                ('calories', models.FloatField()),
                ('time_to_cook', models.IntegerField(help_text='Time in minutes')),
                ('fat', models.FloatField(help_text='Fat in grams')),
                ('carbs', models.FloatField(help_text='Carbohydrates in grams')),
                ('protein', models.FloatField(help_text='Protein in grams')),
                ('ingredients', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='american_recipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('site_url', models.URLField(max_length=500)),
                ('calories', models.FloatField()),
                ('time_to_cook', models.IntegerField(help_text='Time in minutes')),
                ('fat', models.FloatField(help_text='Fat in grams')),
                ('carbs', models.FloatField(help_text='Carbohydrates in grams')),
                ('protein', models.FloatField(help_text='Protein in grams')),
                ('ingredients', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indian_recipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('site_url', models.URLField(max_length=500)),
                ('calories', models.FloatField()),
                ('time_to_cook', models.IntegerField(help_text='Time in minutes')),
                ('fat', models.FloatField(help_text='Fat in grams')),
                ('carbs', models.FloatField(help_text='Carbohydrates in grams')),
                ('protein', models.FloatField(help_text='Protein in grams')),
                ('ingredients', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mexican_recipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
