# Generated by Django 5.0.4 on 2024-04-22 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_savedfive_savedfour_savedone_savedsix_savedthree_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfive',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_five', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedfour',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_four', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedone',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedsix',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_six', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedthree',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_three', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedtwo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
