# Generated by Django 5.0.4 on 2024-04-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_alter_savedfive_user_alter_savedfour_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfive',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savedfive',
            name='carbs',
            field=models.FloatField(help_text='Carbohydrates in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedfive',
            name='fat',
            field=models.FloatField(help_text='Fat in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedfive',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedfive',
            name='ingredients',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='savedfive',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='savedfive',
            name='protein',
            field=models.FloatField(help_text='Protein in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedfive',
            name='site_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedfive',
            name='time_to_cook',
            field=models.IntegerField(help_text='Time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='savedfour',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savedfour',
            name='carbs',
            field=models.FloatField(help_text='Carbohydrates in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedfour',
            name='fat',
            field=models.FloatField(help_text='Fat in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedfour',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedfour',
            name='ingredients',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='savedfour',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='savedfour',
            name='protein',
            field=models.FloatField(help_text='Protein in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedfour',
            name='site_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedfour',
            name='time_to_cook',
            field=models.IntegerField(help_text='Time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='savedone',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savedone',
            name='carbs',
            field=models.FloatField(help_text='Carbohydrates in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedone',
            name='fat',
            field=models.FloatField(help_text='Fat in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedone',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedone',
            name='ingredients',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='savedone',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='savedone',
            name='protein',
            field=models.FloatField(help_text='Protein in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedone',
            name='site_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedone',
            name='time_to_cook',
            field=models.IntegerField(help_text='Time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='savedsix',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savedsix',
            name='carbs',
            field=models.FloatField(help_text='Carbohydrates in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedsix',
            name='fat',
            field=models.FloatField(help_text='Fat in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedsix',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedsix',
            name='ingredients',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='savedsix',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='savedsix',
            name='protein',
            field=models.FloatField(help_text='Protein in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedsix',
            name='site_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedsix',
            name='time_to_cook',
            field=models.IntegerField(help_text='Time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='savedthree',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savedthree',
            name='carbs',
            field=models.FloatField(help_text='Carbohydrates in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedthree',
            name='fat',
            field=models.FloatField(help_text='Fat in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedthree',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedthree',
            name='ingredients',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='savedthree',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='savedthree',
            name='protein',
            field=models.FloatField(help_text='Protein in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedthree',
            name='site_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedthree',
            name='time_to_cook',
            field=models.IntegerField(help_text='Time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='savedtwo',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savedtwo',
            name='carbs',
            field=models.FloatField(help_text='Carbohydrates in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedtwo',
            name='fat',
            field=models.FloatField(help_text='Fat in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedtwo',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedtwo',
            name='ingredients',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='savedtwo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='savedtwo',
            name='protein',
            field=models.FloatField(help_text='Protein in grams', null=True),
        ),
        migrations.AlterField(
            model_name='savedtwo',
            name='site_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedtwo',
            name='time_to_cook',
            field=models.IntegerField(help_text='Time in minutes', null=True),
        ),
    ]
